export type CompositeComponentsNames =
	| '@merely-ui/dropdown-trigger'
	| '@merely-ui/dropdown-content'
	| '@merely-ui/popover-content'
	| '@merely-ui/popover-trigger'
	| '@merely-ui/avatar-badge'
	| '@merely-ui/hint-trigger'
	| '@merely-ui/hint-content'
	| '@merely-ui/modal-close-button'
	| '@merely-ui/modal-header'
	| '@merely-ui/modal-footer'
	| '@merely-ui/modal-overlay'
	| '@merely-ui/modal-body'
	| '@merely-ui/popover-close-button'
	| '@merely-ui/popover-header'
	| '@merely-ui/popover-footer'
	| '@merely-ui/popover-body'
