name: Feature request
description: Suggest an idea for this project
body:
  - type: "markdown"
    attributes:
      value: |
        Thanks for suggesting new feature!
  - type: "textarea"
    id: "description"
    attributes:
      label: "Description"
      description: "Please describe your request in one or two sentences."
    validations:
      required: true
  - type: "textarea"
    id: "justification"
    attributes:
      label: "Problem Statement/Justification"
      description: |
        Is your feature request related to a problem? Please describe.
      placeholder: |
        A clear and concise description of what the problem is. Ex. I'm always frustrated when [...]
    validations:
      required: true
  - type: "textarea"
    id: "proposed-solution"
    attributes:
      label: "Proposed Solution"
      description: |
        Please provide code snippets, gists, or links to the ideal
        design.
    validations:
      required: true
  - type: "textarea"
    id: "alternatives"
    attributes:
      label: "Describe alternatives you've considered"
      description: |
        A clear and concise description of any alternative solutions or features you've considered.
  - type: "textarea"
    id: "additional-information"
    attributes:
      label: "Additional Information"
      description: |
        Add any other additional information or screenshots about the feature request here.
