import { StyleProps } from '../theme-props'

export interface Conditions {
	_hover: StyleProps
	_active: StyleProps
	_focus: StyleProps
	_focusWithin: StyleProps
	_focusVisible: StyleProps
	_disabled: StyleProps
	_visited: StyleProps
	_target: StyleProps
	_readWrite: StyleProps
	_empty: StyleProps
	_checked: StyleProps
	_enabled: StyleProps
	_expanded: StyleProps
	_before: StyleProps
	_after: StyleProps
	_firstLetter: StyleProps
	_firstLine: StyleProps
	_marker: StyleProps
	_selection: StyleProps
	_file: StyleProps
	_backdrop: StyleProps
	_first: StyleProps
	_last: StyleProps
	_notFirst: StyleProps
	_notLast: StyleProps
	_only: StyleProps
	_even: StyleProps
	_odd: StyleProps
	_peerFocus: StyleProps
	_peerHover: StyleProps
	_peerActive: StyleProps
	_peerFocusWithin: StyleProps
	_peerFocusVisible: StyleProps
	_peerDisabled: StyleProps
	_peerChecked: StyleProps
	_peerInvalid: StyleProps
	_peerExpanded: StyleProps
	_peerPlaceholderShown: StyleProps
	_groupFocus: StyleProps
	_groupHover: StyleProps
	_groupActive: StyleProps
	_groupFocusWithin: StyleProps
	_groupFocusVisible: StyleProps
	_groupDisabled: StyleProps
	_groupChecked: StyleProps
	_groupExpanded: StyleProps
	_groupInvalid: StyleProps
	_indeterminate: StyleProps
	_autofill: StyleProps
	_inRange: StyleProps
	_outOfRange: StyleProps
	_placeholder: StyleProps
	_placeholderShown: StyleProps
	_selected: StyleProps
	_default: StyleProps
	_optional: StyleProps
	_fullscreen: StyleProps
	_motionReduce: StyleProps
	_motionSafe: StyleProps
	_print: StyleProps
	_landscape: StyleProps
	_portrait: StyleProps
	_dark: StyleProps
	_light: StyleProps
	_mediaDark: StyleProps
	_mediaLight: StyleProps
	_highContrast: StyleProps
	_lessContrast: StyleProps
	_moreContrast: StyleProps
	_scrollbar: StyleProps
	_scrollbarThumb: StyleProps
	_scrollbarTrack: StyleProps
	_sysDark: StyleProps
	_sysLight: StyleProps
	sm: StyleProps
	smDown: StyleProps
	md: StyleProps
	mdDown: StyleProps
	lg: StyleProps
	lgDown: StyleProps
	xl: StyleProps
	xlDown: StyleProps
	'2xl': StyleProps
	'2xlDown': StyleProps
	_svg: StyleProps
	css: string
}
